services:
  pos-fnb-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: pos-fnb-ui:latest
    container_name: pos-fnb-ui
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8075:3000"
